name: Build and release
on:
  push:
    tags:
      - '*'
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew clean build :cesil-web:shadowJar :cesil-cli:shadowJar
      - name: Package CLI release
        run: |
          mkdir cesil-cli
          cp cesil-cli/build/libs/cesil-cli.jar cesil-cli/
          cp cesil-cli/scripts/cesil cesil-cli/
          chmod +x cesil-cli/cesil
          cp cesil-cli/scripts/cesil.bat cesil-cli/
          zip -r cesil-cli.zip cesil-cli/
      - name: Package web release
        run: |
          mkdir cesil-web
          cp cesil-web/build/libs/cesil-web.jar cesil-web/
          cp cesil-web/scripts/cesilweb cesil-web/
          chmod +x cesil-web/cesilweb
          cp cesil-web/scripts/cesilweb.bat cesil-web/
          zip -r cesil-web.zip cesil-web/
      - name: Release apps
        uses: ncipollo/release-action@v1
        with:
          artifacts: "cesil-cli.zip,cesil-web.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy web app
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku plugins:install java
          heroku deploy:jar cesil-web/build/libs/cesil-web.jar --app ${{ secrets.HEROKU_APP_NAME }} --jdk 11
