name: build-and-deploy
on:
  push:
    paths-ignore:
      - 'README.md'
      - 'html-prototyping/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew clean build :cesil-web:shadowJar
      - name: Store JAR
        uses: actions/upload-artifact@v2
        with:
          name: cesil-emulator
          path: cesil-web/build/libs/cesil-web.jar
          if-no-files-found: error
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set-up Heroku Java plugin
        run: heroku plugins:install java
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: cesil-emulator
      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku deploy:jar /home/runner/work/cesil/cesil/cesil-web.jar --app cesil-interpreter --jdk 11

