name: build-and-deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew clean build shadowJar
      - name: Store JAR
        uses: actions/upload-artifact@v2
        with:
          name: cesil-emulator
          path: build/libs/cesil-emulator.jar
          if-no-files-found: error

