name: Build and release
on:
  push:
    tags:
      - '*'
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew clean build :cesil-web:shadowJar :cesil-cli:shadowJar
      - name: Package CLI release
        run: |
          mkdir -p release/cesil-cli
          cp cesil-cli/build/libs/cesil-cli.jar release/cesil-cli/
          cp cesil-cli/scripts/cesil release/cesil-cli/
          chmod +x release/cesil-cli/cesil
          cp cesil-cli/scripts/cesil.bat release/cesil-cli/
          cd release
          zip -r cesil-cli.zip cesil-cli/
          cd ..
      - name: Package web release
        run: |
          mkdir -p release/cesil-web
          cp cesil-web/build/libs/cesil-web.jar release/cesil-web/
          cp cesil-web/scripts/cesilweb release/cesil-web/
          chmod +x release/cesil-web/cesilweb
          cp cesil-web/scripts/cesilweb.bat release/cesil-web/
          cd release
          zip -r cesil-web.zip cesil-web/
          cd ..
      - name: Release apps
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release/cesil-cli.zip,release/cesil-web.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
