name: Build and release
on:
  push:
    tags:
      - '*'
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew clean build :cesil-web:shadowJar :cesil-cli:shadowJar
      - name: Package CLI app
        run: |
          mkdir cesil
          cp cesil-cli/build/libs/cesil-cli.jar cesil/
          cp cesil-cli/scripts/cesil cesil/
          chmod +x cesil/cesil
          cp cesil-cli/scripts/cesil.bat cesil/
          zip -r cesil.zip cesil/
      - name: Release CLI app
        uses: ncipollo/release-action@v1
        with:
          artifacts: "cesil.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy web app
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku plugins:install java
          heroku deploy:jar cesil-web/build/libs/cesil-web.jar --app ${{ secrets.HEROKU_APP_NAME }} --jdk 11
