name: Tests
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'html-prototyping/**'
    tags-ignore:
      - '**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run tests
        run: ./gradlew clean test
